---
name: drupal

# Common to all services
x-common: &common
  restart: unless-stopped
  tty: true # Required for non-root users with selinux enabled.
  security_opt:
    - label=type:container_runtime_t # Required for selinux to access the docker socket and bind mount files.
  networks:
    default:
networks:
  default:

volumes:
  drupal-private-files: {}
  drupal-public-files: {}
  drupal-solr-config: {}
  mariadb-data: {}
  solr-data: {}

secrets:
  CERT_PUBLIC_KEY:
    file: ./certs/cert.pem
  CERT_AUTHORITY:
    file: ./certs/rootCA.pem
  UID:
    file: ./certs/UID
  DB_ROOT_PASSWORD:
    file: "./secrets/DB_ROOT_PASSWORD"
  DRUPAL_DEFAULT_ACCOUNT_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_ACCOUNT_PASSWORD"
  DRUPAL_DEFAULT_DB_PASSWORD:
    file: "./secrets/DRUPAL_DEFAULT_DB_PASSWORD"
  DRUPAL_DEFAULT_SALT:
    file: "./secrets/DRUPAL_DEFAULT_SALT"

services:
  init:
    image: libops/base@sha256:4a8d3997ac565981cd91ca36fd5a2b64955bac8d78a3632abd5a7137609be631
    restart: no
    networks:
      default:
    volumes:
      - ./.env:/.env
      - ./certs:/certs:rw
      - ./secrets:/secrets:rw
      - ./scripts:/scripts:ro
      - ./docker-compose.yml:/docker-compose.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:z
    security_opt:
      - label=type:container_runtime_t
    entrypoint: /scripts/init-entrypoint.sh
    profiles: [none]

  mariadb:
    <<: *common
    image: libops/mariadb:11@sha256:df935aa57a4444a1bd9024afdf8b3d78abfdfa2c4662320badd099fa6193de6b
    secrets:
      - source: DB_ROOT_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql:rw

  drupal:
    <<: *common
    image: libops/drupal:php84
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      pull: true
      args:
        BASE_IMAGE: libops/drupal:php84
      x-bake:
        platforms: [linux/amd64, linux/arm64]
        cache-from:
          - type=registry,ref=libops/drupal:php84
        cache-to:
          - type=inline
    environment:
      DEVELOPMENT_ENVIRONMENT: "false"
      DRUPAL_DEFAULT_CONFIGDIR: "/var/www/drupal/config/sync"
      DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG: "true"
      DRUPAL_DEFAULT_NAME: "Drupal-Website"
      DRUPAL_DEFAULT_PROFILE: "minimal"
      DRUPAL_DEFAULT_SITE_URL: "${DOMAIN}"
      DRUPAL_DEFAULT_SOLR_HOST: "solr"
      DRUPAL_DEFAULT_SOLR_CORE: "default"
      DRUPAL_DEFAULT_SOLR_PORT: "8983"
      DRUSH_OPTIONS_URI: "${SITE_URL:-${URI_SCHEME:-http}://${DOMAIN}}"
      DRUPAL_ENABLE_HTTPS: "false"
      LIBOPS_SMTP_HOST: host.docker.internal
      LIBOPS_SMTP_PORT: "25"
    healthcheck:
      start_period: 10s
    secrets:
      - source: DB_ROOT_PASSWORD
      - source: DRUPAL_DEFAULT_ACCOUNT_PASSWORD
      - source: DRUPAL_DEFAULT_DB_PASSWORD
        target: DB_PASSWORD
      - source: DRUPAL_DEFAULT_SALT
      - source: CERT_AUTHORITY
      - source: UID
    volumes:
      - type: volume
        source: drupal-public-files
        target: /var/www/drupal/web/sites/default/files
        read_only: false
      - type: volume
        source: drupal-private-files
        target: /var/www/drupal/private
        read_only: false
      - drupal-solr-config:/opt/solr/server/solr/default:z,rw
      - ./config:/var/www/drupal/config:z,rw

  solr:
    <<: *common
    image: libops/solr:9@sha256:da3127bddee9404e6428f8fb927d63a68ee93476022de96c021dffaea78b3537
    volumes:
      - solr-data:/data:rw
      - type: volume
        source: drupal-solr-config
        target: /opt/solr/server/solr/default
        read_only: false
        volume:
          nocopy: true
    depends_on:
      drupal:
        condition: service_healthy

  traefik:
    <<: *common
    image: traefik:v3.7.4@sha256:fcdef599e6259359833dd2e1d49f9e964f66825d69bd3dd468f51102ce013d03
    command: >-
      --ping=true
      --log.level=INFO
      --entryPoints.http.address=:80
      --entryPoints.http.transport.respondingTimeouts.readTimeout=300s
      --providers.file.directory=/etc/traefik/dynamic
      --providers.docker=true
      --providers.docker.network=default
      --providers.docker.exposedByDefault=false
      --api.insecure=false
      --api.dashboard=false
      --api.debug=false
    environment:
      URI_SCHEME: http
      DOMAIN: ${DOMAIN}
      DEVELOPMENT_ENVIRONMENT: "false"
    ports:
      - "${HOST_INSECURE_PORT:-80}:80"
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./conf/traefik:/etc/traefik/dynamic:ro
    healthcheck:
      test: traefik healthcheck --ping
      start_period: 10s
    networks:
      default:
        aliases:
          - ${DOMAIN}
          - solr.${DOMAIN}
    depends_on:
      drupal:
        condition: service_healthy
