SHELL := /bin/bash

.PHONY: help rollout clean test lint
.SILENT:

-include custom.Makefile

help: ## Show this help message
	echo 'Usage: make [target]'
	echo ''
	echo 'Available targets:'
	awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%s\033[0m\t%s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort | column -t -s $$'\t'

rollout: ## Roll out the currently checked out Drupal stack
	./scripts/rollout.sh

clean: ## Delete stateful local data generated by the template
	./scripts/clean.sh

test: ## Run custom Drupal tests
	./scripts/test.sh

lint: ## Lint custom Drupal code
	./scripts/lint.sh
